Fix potential torchvision error due to dependency conflict
Installing torchvision with legacy resolver could cause the installed version of torch conflict with the required version from torchvision, leading to errors like `RuntimeError: operator torchvision::nms does not exist` or `AttributeError: partially initialized module 'torchvision' has no attribute 'extension'`