fix: attribute error
When `strict_type_constraints` is `True`, accessing `trt.BuilderFlag.STRICT_TYPES` causes `AttributeError: type object 'tensorrt.tensorrt.BuilderFlag' has no attribute 'STRICT_TYPES'`.
Indeed, there is no such builder flag in TensorRT, and should be replaced by `trt.BuilderFlag.OBEY_PRECISION_CONSTRAINTS`.